### ISSUE TITLE
over not found in @stomp/stompjs

### ISSUE THREAD

**Issue by rachid822** [g00glen00b/spring-boot-angular-websockets#1]
Hello,

Thank you so much for this nice tuto.
I have following error with angular 9

ERROR in src/app/shared/service/websocket.service.ts:4:27 - error TS2305: Module '"../../../../node_modules/@stomp/stompjs"' has no exported member 'over'.

    4 import { Client, Message, over, StompSubscription } from '@stomp/stompjs';

Do you have any idea please?
Best regards,
Rachid

**Comment by g00glen00b** [comment]
Which version of the stompjs library are you using? The API for declaring a stompjs client has changed significantly, and the `over` function is no longer available since version 5 and onwards.  Apparantly, [you have to set a `webSocketFactory` now](https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/using-stomp-with-sockjs.html).
