### ISSUE TITLE
Need an understanding of why BehaviorSubject was used

### ISSUE THREAD

**Issue by manoj1492** [g00glen00b/spring-boot-angular-websockets#2]
Hi Dimitri,

I have read your tutorial on angular websockets and its smooth and easy to read. However I couldn;t understand one line which I am posting here from the blog.
" connect() callback only fires once, even if multiple callbacks are added before the WebSocket connection is made".

Can you please explain this in some more detail.

Thanks!

**Comment by g00glen00b** [comment]
The problem is that you only want to pass the websocket if the connection is ready. To know whether or not the connection is ready, you have to listen to the `connect()` callback:

```javascript
const conn = over(new SockJS('http://localhost:8080/live'));
conn.connect({}, () => {
  // The connection is ready
});
```

The question is, how are you going to do that with observables? With the cold observable it was easy, as we could use `observer.next()` to actually pass the connection as soon as it's ready. To do that, you could do something like this:

```javascript
const conn = over(new SockJS('http://localhost:8080/live'));
return new Observable(observer => {
  conn.connect({}, () => observer.next(conn));
});
```

However, this won't work with hot observables, because the `connect()` callback is only fired once. That means that only the first (hot) observable would work and all the others won't, because the `observer.next(conn)` will never be triggered.

To solve that, you basically want to do the following:

- If the `conn.connect()` callback has been triggered already: immediately return the connection as it's ready
- If the callback hasn't been triggered, we have to wait until `conn.connect()` completes before we can return the connection. Otherwise, if we wouldn't wait, it could happen that someone tries to use the websocket before it's even ready

That means that we somehow have to "store" the connection state (connected or not), and to do that, I'm using a `BehaviorSubject`. The reason for that is because a `BehaviorSubject` stores its current value, and returns it when someone subscribes to it.

So that's how I came up with the `SocketClientService` within my blogpost. What happens there is the following:

1. It creates the WebSocket connection
2. It creates the `BehaviorSubject` with the value "ATTEMPTING"
3. It calls the `conn.connect()` method

What happens afterwards, depends on when the `SocketClientService.connect()` method is fired. If it was fired immediately, before the `conn.connect()` callback was fired, then the following would happen:

1. It subscribes to the `BehaviorSubject` and gets the value "ATTEMPTING"
2. It filters out that value, and thus, doesn't return a connection
3. As soon as the `conn.connect()` callback is called, the state changes to "CONNECTED"
4. The new value "CONNECTED" is received by the subscriber, which isn't filtered out, and thus, `observer.next(this.client)` is fired to pass the connection now that it's ready

If someone else calls `SocketClientService.connect()` now, the following would happen:

1. It subscribes to the `BehaviorSubject` and gets the value "CONNECTED"
2. The value "CONNECTED" is received by the subscriber, and thus, `observer.next(this.client)` is fired to pass the connection now that it's ready
